Map<String, String> ar = {
  'communicate with friends': 'تواصل مع أصدقائك الآن',
  'comments': 'تعليقات',
  'write a comment...': 'أكتب تعليق ...',
  'Like': 'أعجبني',
  'Share': 'مشاركة',
  'Send Message': 'أرسل رسالة',
  'View': 'مشاهدة',
  'Delete': 'حذف',
  'People who commented': 'الذين قاموا بالتعليق',
  'Public': 'عام',
  'Create Post': 'أضف مشاركة',
  'People who liked': 'الذين قاموا بالأعجاب',
  'LOGIN': 'تسجيل الدخول',
  'login': 'تسجيل الدخول',
  'Login now to communicate with your friends':
      'سجل الآن لكي تتواصل مع أصدقائك',
  'Don\'t have an account?': 'لا تمتلك حساب ؟',
  'REGISTER': 'أنشاء حساب',
  'Register now to communicate with your friends':
      'أنشئ حساب الآن لكي تتواصل مع أصدقائك',
  'Search': 'بحث',
  'Edit Profile': 'تعديل الحساب',
  'No posts yet': 'لا يوجد بايانات',
  'Add Photos': 'أضف صور',
  'add photos': 'أضف صور',
  'Following': 'متابعين',
  'Followers': 'معجبين',
  'Photos': 'صور',
  'Post': 'منشور',
  'POST': 'أنشر',
  'Posts': 'منشورات',
  'News Feed': 'آخر الأخبار',
  'Chats': 'دردشة',
  'New Post': 'منشور جديد',
  'Friends': 'الأصدقاء',
  'Settings': 'الملف الشخصي',
  'what is in you mind,': 'ما الذي يوجد في بالك',
  'Notification': 'الأشعارات',
  'Light': 'مضيء',
  'Dark': 'مظلم',
  'Logout': 'تسجيل الخروج',
  'register': 'تسجيل حساب جديد',
  'Name': 'الأسم',
  'Must add name': 'يجب أضافة الأسم',
  'Email': 'البريد الإلكتروني',
  'Must add email address': 'يجب أضافة الإيميل',
  'Password': 'كلمة السر',
  'Password is too short': 'كلمة السر ضعيفة',
  'Confirm Password': 'تأكيد كلمة السر',
  'Must add password': 'يجب أضافة كلمة السر',
  'Password not match': 'كلمة السر غير متوافقة',
  'Phone': 'رقم الموبايل',
  'Must add phone': 'يجب أضافة رقم الموبايل',
  'Welcome': 'مرحباً',
  'UPDATE': 'تعديل',
  'Bio': 'السيرة الذاتية',
  'Must add Bio': 'يجب أضافة السيرة الذاتية',
  'press back one more time to exit': 'press back one more time to exit',
};
