Map<String, String> en = {
  'communicate with friends': 'communicate with friends',
  'comments': 'comments',
  'write a comment...': 'write a comment...',
  'Like': 'Like',
  'Share': 'Share',
  'Send Message': 'Send Message',
  'View': 'View',
  'Delete': 'Delete',
  'People who commented': 'People who commented',
  'Public': 'Public',
  'Create Post': 'Create Post',
  'People who liked': 'People who liked',
  'LOGIN': 'LOGIN',
  'login': 'login',
  'Login now to communicate with your friends':
      'Login now to communicate with your friends',
  'Don\'t have an account?': 'Don\'t have an account?',
  'REGISTER': 'REGISTER',
  'Register now to communicate with your friends':
      'Register now to communicate with your friends',
  'Search': 'Search',
  'Edit Profile': 'Edit Profile',
  'No posts yet': 'No posts yet',
  'Add Photos': 'Add Photos',
  'add photos': 'add photos',
  'Following': 'Following',
  'Followers': 'Followers',
  'Photos': 'Photos',
  'Post': 'Post',
  'POST': 'POST',
  'Posts': 'Posts',
  'News Feed': 'News Feed',
  'Chats': 'Chats',
  'New Post': 'New Post',
  'Friends': 'Friends',
  'Settings': 'Settings',
  'what is in you mind,': 'what is in you mind,',
  'Notifications': 'Notifications',
  'Light': 'Light',
  'Dark': 'Dark',
  'Logout': 'Logout',
  'register': 'register',
  'Name': 'Name',
  'Must add name': 'Must add name',
  'Email': 'Email',
  'Must add email address': 'Must add email address',
  'Password': 'Password',
  'Password is too short': 'Password is too short',
  'Confirm Password': 'Confirm Password',
  'Must add password': 'Must add password',
  'Password not match': 'Password not match',
  'Phone': 'Phone',
  'Must add phone': 'Must add phone',
  'Welcome': 'Welcome',
  'UPDATE': 'UPDATE',
  'Bio': 'Bio',
  'Must add Bio': 'Must add Bio',
  'press back one more time to exit': 'press back one more time to exit',
  'Classic Mode': 'Classic Mode',
  'Modern Mode': 'Modern Mode',
};
